name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  registry: docker.pkg.github.com

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker.pkg.github.com
      uses: azure/docker-login@v1
      with: 
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Export image tag value
      run: echo '::set-env name=TAG::${{ env.registry }}/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.sha }}'
    - name: Build and publish the Docker image
      run: |
        docker build . --file Dockerfile --tag ${TAG}
        docker push ${TAG}
        docker tag ${TAG} ${registry}/${{ github.actor }}/${{ github.event.repository.name }}:latest
        docker push ${registry}/${{ github.actor }}/${{ github.event.repository.name }}:latest        
