name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  registry: docker.pkg.github.com

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker.pkg.github.com
      uses: azure/docker-login@v1
      with: 
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and publish the Docker image
      env:
        tag: ${registry}/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag ${tag}
        docker push ${tag}
        docker tag ${tag} ${registry}/${{ github.actor }}/${{ github.event.repository.name }}:latest
        docker push ${registry}/${{ github.actor }}/${{ github.event.repository.name }}:latest        
