name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and publish the Docker image to Github Packages
      env:
        tag: docker.pkg.github.com/svejk-ciber/${{ github.event.repository.name }}:${{ github.sha }}
#    - uses: actions/checkout@v2
      uses: azure/docker-login@v1
      with: 
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker build . --file Dockerfile --tag ${tag}
        docker push ${tag}
        docker tag ${tag} docker.pkg.github.com/svejk-ciber/${{ github.event.repository.name }}:latest
        docker push docker.pkg.github.com/svejk-ciber/${{ github.event.repository.name }}:latest        
